version: '3.8'

services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    ports:
      - "9393:9300"
    environment:
      - CSVSERVER_BORDER=${CSVSERVER_BORDER}
    env_file:
      - ./csvserver.env
    
